version : '3'
services :

  db:
    build: ./mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  redis:
    build: ./redis
    ports: 
      - "6379:6379"

  golang:
    build: 
      context: ./golang
    ports:
      - "8080:8080"
    volumes:
      - ${PROJECT_SRC}:/var/www
    environment:
      - PORT=8080

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "php"
    volumes:
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
      - "${WORDPRESS_DIR}:/var/www"
      - "${NGINX_LOGS_DIR}:/var/log/nginx"
  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - "${WORDPRESS_DIR}:/var/www"

