version : '3'
services :

  db:
    build: ./mysql
    ports:
      - "33060:3306"

  redis:
    build: ./redis
    ports: 
      - "6379:6379"

  golang:
    build: ./golang
    ports:
      - "8080:80"

