version : '3'
services :

  db:
    build: ./mysql
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    build: ./redis
    ports: 
      - "6379:6379"

  golang:
    build: ./golang
    ports:
      - "8080:8080"

